name: Push Docker Images (Dev & Prod)

on:
  push:
    branches: [ "dev", "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: docker build . --file dockerfile-prod --tag ${{ secrets.DOCKER_USERNAME }}/surtex-prod-api:${{ github.sha }}
      - name: Build the Docker image
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: docker build . --file dockerfile-dev --tag ${{ secrets.DOCKER_USERNAME }}/surtex-inventory:${{ github.sha }}
      - name: Push the Docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: docker push ${{ secrets.DOCKER_USERNAME }}/surtex-prod-api:${{ github.sha }}
      - name: Push the Docker image
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: docker push ${{ secrets.DOCKER_USERNAME }}/surtex-inventory:${{ github.sha }}
