name: Production Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub (replace with your registry)
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u denam98 --p BmDenuwan@199899
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/surtex-prod-api:${{ github.sha }}
      - name: Push the Docker image (replace with your registry)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: docker push ${{ secrets.DOCKER_USERNAME }}/surtex-prod-api:${{ github.sha }}
